Restricted#145
BYU-ODH/y-video-back-end pull request #149
Opened 2023-08-20 00:07 UTC by WorldsEndless

closes #145

2023-09-02 01:43 UTC, reynoldsnlp requested changes
Look at my comments to see a few things that might need to be cleaned up. Thank you so much for figuring this out!!

2023-09-02 01:43 UTC, reynoldsnlp commented on src/clj/y_video_back/db/core.clj
Is the `#_#_true (spy);` line for debugging only? I.e., should it be re-commented?

2023-09-02 01:43 UTC, reynoldsnlp commented on src/clj/y_video_back/routes/home.clj
Should the `(comment ...)` be deleted?

2023-09-02 01:43 UTC, reynoldsnlp commented on src/clj/y_video_back/routes/service_handlers/handlers/user_handlers.clj
Should this `(comment ...)` be deleted, too?

2023-09-02 01:43 UTC, reynoldsnlp commented on test/clj/unit/y_video_back/db/words_test.clj
All of these renamed tests would have a cleaner git history if you use `git mv` instead of just `mv`.

2023-09-02 01:44 UTC, reynoldsnlp commented on test/clj/unit/y_video_back/db/words_test.clj
This doesn't need to be changed for this PR, just FYI.

2023-09-02 12:17 UTC, WorldsEndless commented
Thanks for catching these! A few of them were already there and I can recomment them. In general the first success was getting the Github to pass and then the cleanup should occur, with many comments (especially the "Rich Comments" in `comment` blocks) will be extraccted into tests themselves. At least, that's the idea. Thanks for reminding me!

2023-09-02 19:12 UTC, WorldsEndless commented
I have cleaned up that code and made sure the rich comments are represented in tests. I'll keep the git-mv command in mind for the future; I'm not sure there is much to be done right now. What differences do you see from just doing a bulk "mv" on the files to doing a "git-mv"? Each file also had to be edited because the jvm requires filename changes to be reflected in the internal namespace declaration.

2023-09-21 18:33 UTC, WorldsEndless commented
@reynoldsnlp is there anything else you wanted on this?

2023-09-21 21:41 UTC, reynoldsnlp approved these changes
lgtm

2023-09-21 21:41 UTC, merged