Safari#120
BYU-ODH/y-video-back-end pull request #165
Opened 2024-01-17 23:16 UTC by WorldsEndless

closes #120. 

Applies content-type of `video/mp4` to everything. Are there other types we serve? (This is tricky because no file extensions are provided to the service handler)

2024-03-06 18:39 UTC, WorldsEndless commented
This one is awaiting testing on apple devices. It should be merge-able, though, because the worst it can do is leave those who are already broken still broken.

2024-03-15 22:21 UTC, reynoldsnlp commented on src/clj/y_video_back/middleware.clj
> +      ;;ring-content/wrap-content-type
Delete this comment?

2024-03-15 22:24 UTC, reynoldsnlp commented on src/clj/y_video_back/routes/service_handlers/handlers/media_handlers.clj
> +(defn extension [s]
I don't know if using short variables like `s` (for "string"?) is conventional in Clojure, but I think more verbose variable names are almost always readable/maintainable. The only exception I make for myself is when it is strongly suggests by context, e.g. `for s in strings`.

2024-03-15 22:28 UTC, reynoldsnlp requested changes
Tiny edits requested.

2024-03-19 16:19 UTC, reynoldsnlp approved these changes
lgtm

2024-03-19 16:37 UTC, merged